# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'The Rick and Morty Characters' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for The Rick and Morty Characters
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  
  target 'The Rick and Morty Characters Tests' do
    pod 'Firebase'
  end
end
